export const APP_INFO = {
  name: 'OH SEJIN',
  title: 'OH SEJIN',
  titleTemplate: '%s | OH SEJIN',
  description: `
    'Designer + Developer Oh Sejin. 디자인과 코드 사이를 연결하며, 아이디어를 현실에서 작동하는 경험으로 설계하고 구현합니다. Based in Seoul, South Korea.',
  `,
  keywords: [
    '오세진',
    '웹 디자이너',
    '그래픽 디자이너',
    '웹 개발자',
    '인터랙티브 디자인',
    '프론트엔드 개발',
    '디지털 경험',
    '기술과 예술',
    '웹 접근성',
    '웹',
    '인터랙션',
    '디자인',
    '개발',
    '프론트엔드',
    '프론트엔드 개발자',
    '웹 디자인',
    '그래픽 디자인',
    '웹 개발',
    'SEJIN OH',
    'OH SEJIN',
    'web designer',
    'graphic designer',
    'web developer',
    'interactive design',
    'frontend developer',
    'digital experiences',
    'technology and art',
    'web accessibility',
    'web',
    'interaction',
    'design',
    'development',
    'frontend',
    'frontend developer',
    'web design',
    'graphic design',
    'web development',
  ],
  authors: [
    {
      name: 'OH SEJIN',
      url: 'https://ohsejin.com',
    },
  ],
  url: 'https://ohsejin.com',
  google_site_verification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
}
